# Generated by Django 5.0.6 on 2024-05-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0003_remove_entry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='imagen'),
        ),
    ]
